# $Id: //depot/sw/qca_main/components/os/linux-2.6.31/1.0/arch/cris/arch-v32/mach-a3/Makefile#1 $
#
# Makefile for the linux kernel.
#

obj-y   := dma.o pinmux.o io.o arbiter.o
obj-$(CONFIG_ETRAX_VCS_SIM) += vcs_hook.o
obj-$(CONFIG_CPU_FREQ)   += cpufreq.o

clean:

